In [37]:
import pandas as pd

In [38]:
# Load the CSV file in a DataFrame.
df = pd.read_csv('../data/raw/supply_chain_levels.csv')
df

,Supply Chain Level,Description,Companies
0,1. Upstream Mining & Raw Materials,Extraction and primary processing of essential...,"MP Materials, USA Rare Earth, Lynas Rare Earth..."
1,2. Material Refining & Advanced Structure,Chemical processing and advanced synthesis of ...,"Toray Industries, Hexcel, Mitsubishi Chemical ..."
2,3. Robot AI & Foundation Models,"Foundational physical artificial intelligence,...","NVIDIA, Google DeepMind, OpenAI, Physical Inte..."
3,"4. Simulation, Training & Robot OS","Physics-based digital twin environments, synth...","NVIDIA (Isaac), Google DeepMind (MuJoCo), Open..."
4,5. Compute & Edge AI Chips,"On-board processing silicon, edge AI accelerat...","NVIDIA, Qualcomm, AMD, Intel, Ambarella, Latti..."
5,"6. Power, Energy & Thermal Systems","High energy-density battery cells, intelligent...","CATL, LG Energy Solution, Samsung SDI, Panason..."
6,7. Sensors & Perception Systems,"Environmental spatial sensing arrays (LiDAR, s...","Sony, Samsung Electronics, Hesai Group, Ouster..."
7,"8. Actuators, Joints & Motion Control",Primary mechatronic movement stack consisting ...,"Harmonic Drive Systems, LeaderDrive, Nabtesco,..."
8,9. Actuator Assembly & Dexterous Hands,Subsystem contract assembly integrating motors...,"Sanhua Intelligent Controls, Tuopu Group, Zhao..."
9,10. Humanoid OEMs & System Builders,Prime Original Equipment Manufacturers that ar...,"Tesla (Optimus), Figure AI, Agility Robotics, ..."
10,11. System Integrators & Industrial Automation,"Tier-1 engineering integrators that embed, pro...","Siemens, ABB, KUKA, FANUC, Yaskawa Electric, F..."
11,12. Deployment & End-User Enterprises,Enterprise commercial customers deploying robo...,"Amazon, BMW, Mercedes-Benz, Hyundai Motor Grou..."
12,"13. Aftermarket, Services & Lifecycle Management",Ongoing operational infrastructure providing p...,"Uptake, PTC, ServiceNow, Zendesk, TeamViewer, ..."

# Cleaning

Separate *Supply Chain Level* colomn in 2: the supply chain level (number) and its name.

In [39]:
df['chain_level_nb'] = df['Supply Chain Level'].str.extract(r'(\d+)').astype(int)
df['chain_level'] = df['Supply Chain Level'].str.extract(r'\d+\.\s*(.*)')
df

,Supply Chain Level,Description,Companies,chain_level_nb,chain_level
0,1. Upstream Mining & Raw Materials,Extraction and primary processing of essential...,"MP Materials, USA Rare Earth, Lynas Rare Earth...",1,Upstream Mining & Raw Materials
1,2. Material Refining & Advanced Structure,Chemical processing and advanced synthesis of ...,"Toray Industries, Hexcel, Mitsubishi Chemical ...",2,Material Refining & Advanced Structure
2,3. Robot AI & Foundation Models,"Foundational physical artificial intelligence,...","NVIDIA, Google DeepMind, OpenAI, Physical Inte...",3,Robot AI & Foundation Models
3,"4. Simulation, Training & Robot OS","Physics-based digital twin environments, synth...","NVIDIA (Isaac), Google DeepMind (MuJoCo), Open...",4,"Simulation, Training & Robot OS"
4,5. Compute & Edge AI Chips,"On-board processing silicon, edge AI accelerat...","NVIDIA, Qualcomm, AMD, Intel, Ambarella, Latti...",5,Compute & Edge AI Chips
5,"6. Power, Energy & Thermal Systems","High energy-density battery cells, intelligent...","CATL, LG Energy Solution, Samsung SDI, Panason...",6,"Power, Energy & Thermal Systems"
6,7. Sensors & Perception Systems,"Environmental spatial sensing arrays (LiDAR, s...","Sony, Samsung Electronics, Hesai Group, Ouster...",7,Sensors & Perception Systems
7,"8. Actuators, Joints & Motion Control",Primary mechatronic movement stack consisting ...,"Harmonic Drive Systems, LeaderDrive, Nabtesco,...",8,"Actuators, Joints & Motion Control"
8,9. Actuator Assembly & Dexterous Hands,Subsystem contract assembly integrating motors...,"Sanhua Intelligent Controls, Tuopu Group, Zhao...",9,Actuator Assembly & Dexterous Hands
9,10. Humanoid OEMs & System Builders,Prime Original Equipment Manufacturers that ar...,"Tesla (Optimus), Figure AI, Agility Robotics, ...",10,Humanoid OEMs & System Builders
10,11. System Integrators & Industrial Automation,"Tier-1 engineering integrators that embed, pro...","Siemens, ABB, KUKA, FANUC, Yaskawa Electric, F...",11,System Integrators & Industrial Automation
11,12. Deployment & End-User Enterprises,Enterprise commercial customers deploying robo...,"Amazon, BMW, Mercedes-Benz, Hyundai Motor Grou...",12,Deployment & End-User Enterprises
12,"13. Aftermarket, Services & Lifecycle Management",Ongoing operational infrastructure providing p...,"Uptake, PTC, ServiceNow, Zendesk, TeamViewer, ...",13,"Aftermarket, Services & Lifecycle Management"

Rename the description column to lower case.

In [44]:
df = df.rename(columns={'Description' : 'description'})
df

,Supply Chain Level,description,Companies,chain_level_nb,chain_level
0,1. Upstream Mining & Raw Materials,Extraction and primary processing of essential...,"MP Materials, USA Rare Earth, Lynas Rare Earth...",1,Upstream Mining & Raw Materials
1,2. Material Refining & Advanced Structure,Chemical processing and advanced synthesis of ...,"Toray Industries, Hexcel, Mitsubishi Chemical ...",2,Material Refining & Advanced Structure
2,3. Robot AI & Foundation Models,"Foundational physical artificial intelligence,...","NVIDIA, Google DeepMind, OpenAI, Physical Inte...",3,Robot AI & Foundation Models
3,"4. Simulation, Training & Robot OS","Physics-based digital twin environments, synth...","NVIDIA (Isaac), Google DeepMind (MuJoCo), Open...",4,"Simulation, Training & Robot OS"
4,5. Compute & Edge AI Chips,"On-board processing silicon, edge AI accelerat...","NVIDIA, Qualcomm, AMD, Intel, Ambarella, Latti...",5,Compute & Edge AI Chips
5,"6. Power, Energy & Thermal Systems","High energy-density battery cells, intelligent...","CATL, LG Energy Solution, Samsung SDI, Panason...",6,"Power, Energy & Thermal Systems"
6,7. Sensors & Perception Systems,"Environmental spatial sensing arrays (LiDAR, s...","Sony, Samsung Electronics, Hesai Group, Ouster...",7,Sensors & Perception Systems
7,"8. Actuators, Joints & Motion Control",Primary mechatronic movement stack consisting ...,"Harmonic Drive Systems, LeaderDrive, Nabtesco,...",8,"Actuators, Joints & Motion Control"
8,9. Actuator Assembly & Dexterous Hands,Subsystem contract assembly integrating motors...,"Sanhua Intelligent Controls, Tuopu Group, Zhao...",9,Actuator Assembly & Dexterous Hands
9,10. Humanoid OEMs & System Builders,Prime Original Equipment Manufacturers that ar...,"Tesla (Optimus), Figure AI, Agility Robotics, ...",10,Humanoid OEMs & System Builders
10,11. System Integrators & Industrial Automation,"Tier-1 engineering integrators that embed, pro...","Siemens, ABB, KUKA, FANUC, Yaskawa Electric, F...",11,System Integrators & Industrial Automation
11,12. Deployment & End-User Enterprises,Enterprise commercial customers deploying robo...,"Amazon, BMW, Mercedes-Benz, Hyundai Motor Grou...",12,Deployment & End-User Enterprises
12,"13. Aftermarket, Services & Lifecycle Management",Ongoing operational infrastructure providing p...,"Uptake, PTC, ServiceNow, Zendesk, TeamViewer, ...",13,"Aftermarket, Services & Lifecycle Management"

Export a clean file.

In [45]:
df_clean = df[['chain_level_nb', 'description', 'chain_level']].copy()
df_clean

,chain_level_nb,description,chain_level
0,1,Extraction and primary processing of essential...,Upstream Mining & Raw Materials
1,2,Chemical processing and advanced synthesis of ...,Material Refining & Advanced Structure
2,3,"Foundational physical artificial intelligence,...",Robot AI & Foundation Models
3,4,"Physics-based digital twin environments, synth...","Simulation, Training & Robot OS"
4,5,"On-board processing silicon, edge AI accelerat...",Compute & Edge AI Chips
5,6,"High energy-density battery cells, intelligent...","Power, Energy & Thermal Systems"
6,7,"Environmental spatial sensing arrays (LiDAR, s...",Sensors & Perception Systems
7,8,Primary mechatronic movement stack consisting ...,"Actuators, Joints & Motion Control"
8,9,Subsystem contract assembly integrating motors...,Actuator Assembly & Dexterous Hands
9,10,Prime Original Equipment Manufacturers that ar...,Humanoid OEMs & System Builders
10,11,"Tier-1 engineering integrators that embed, pro...",System Integrators & Industrial Automation
11,12,Enterprise commercial customers deploying robo...,Deployment & End-User Enterprises
12,13,Ongoing operational infrastructure providing p...,"Aftermarket, Services & Lifecycle Management"

In [46]:
df_clean.to_csv('../data/processed/supply_chain_levels_clean.csv', index=False)