In [33]:
import pandas as pd

In [34]:
# Load the CSV file in a DataFrame.
df = pd.read_csv('../data/raw/stocks.csv')

# Cleaning

In [35]:
# Extract the ticker (only keep the first if multiple values are present - usually due to multiple cotations)
df['ticker'] = df['ticker'].str.extract(r'^([^(/]+)', expand=False).str.strip()
df.head(30)

                            company      ticker                      Layer
0                      MP Materials          MP                    Layer 1
1                    USA Rare Earth        USAR                    Layer 1
2                 Lynas Rare Earths         LYC                    Layer 1
3                      Energy Fuels        UUUU                    Layer 1
4                         Albemarle         ALB                    Layer 1
5                               SQM         SQM                    Layer 1
6                   Ganfeng Lithium      002460                    Layer 1
7                  Toray Industries        3402                    Layer 2
8                            Hexcel         HXL                    Layer 2
9         Mitsubishi Chemical Group        4188                    Layer 2
10                               3M         MMM                    Layer 2
11                           DuPont          DD                    Layer 2
12                             BASF         BAS                    Layer 2
13                         Covestro        1COV                    Layer 2
14                             MTIG     Private                    Layer 2
15                           Evonik         EVK                    Layer 2
16                    ArcelorMittal          MT                    Layer 2
17                           NVIDIA        NVDA  Layer 3, Layer 4, Layer 5
18                  Google DeepMind       GOOGL           Layer 3, Layer 4
19                           OpenAI     Private                    Layer 3
20            Physical Intelligence     Private                    Layer 3
21                         Skild AI     Private                    Layer 3
22                        Covariant     Private                    Layer 3
23                   Meta Platforms        META                    Layer 3
24                     Sanctuary AI     Private          Layer 3, Layer 10
25                          iFlytek      002230                    Layer 3
26  Open Source Robotics Foundation  Non-Profit                    Layer 4
27               Unity Technologies           U                    Layer 4
28                       Epic Games     Private                    Layer 4
29                        Intrinsic       GOOGL                    Layer 4

Remove non publicly traded companies.

In [36]:
remove_private = (df["ticker"].isin(["Private","Non-Profit","Non-Profit / Research Institute"]) == False)
df_private = df[remove_private]
df_private

               company  ticker     Layer
0         MP Materials      MP   Layer 1
1       USA Rare Earth    USAR   Layer 1
2    Lynas Rare Earths     LYC   Layer 1
3         Energy Fuels    UUUU   Layer 1
4            Albemarle     ALB   Layer 1
..                 ...     ...       ...
133                PTC     PTC  Layer 13
134         ServiceNow     NOW  Layer 13
136         TeamViewer     TMV  Layer 13
137            Trimble    TRMB  Layer 13
138        Samsung SDS  018260  Layer 13

[105 rows x 3 columns]

Identify potential duplicates to handle.

In [37]:
df_private[df_private["ticker"].duplicated(keep=False)]

                 company  ticker             Layer
18       Google DeepMind   GOOGL  Layer 3, Layer 4
29             Intrinsic   GOOGL           Layer 4
81            Kollmorgen     RRX           Layer 8
89         Regal Rexnord     RRX           Layer 8
104      Boston Dynamics  005380          Layer 10
126  Hyundai Motor Group  005380          Layer 12

I will need to group by tickers and aggregate Layers. Company names can be dropped as I can find them later with the yfinance library via the ticker.

In [38]:
df_private = df_private.drop(["company"], axis=1)
df_private

     ticker     Layer
0        MP   Layer 1
1      USAR   Layer 1
2       LYC   Layer 1
3      UUUU   Layer 1
4       ALB   Layer 1
..      ...       ...
133     PTC  Layer 13
134     NOW  Layer 13
136     TMV  Layer 13
137    TRMB  Layer 13
138  018260  Layer 13

[105 rows x 2 columns]

---

Rename the *Layer* column to *layer* (lowercase).

In [39]:
df_cleaned = df_private.rename(columns={"Layer" : "layer"})
df_cleaned.columns

Index(['ticker', 'layer'], dtype='str')

---

Create a simple dataset with only the tickers.

In [40]:
df_tickers = df_cleaned.drop(["layer"], axis=1)
df_tickers

     ticker
0        MP
1      USAR
2       LYC
3      UUUU
4       ALB
..      ...
133     PTC
134     NOW
136     TMV
137    TRMB
138  018260

[105 rows x 1 columns]

# Export

In [41]:
df_cleaned.to_csv('../data/processed/stocks_cleaned.csv', index=False)
df_tickers.to_csv('../data/processed/tickers.csv', index=False)